package Mapeamentos;
// Generated 15/10/2018 14:46:52 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,schema="public"
)
public class Compra  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Produto produto;
     private Date data;
     private Integer quantCompra;
     private Double valorTotal;

    public Compra() {
    }

	
    public Compra(int id) {
        this.id = id;
    }
    public Compra(int id, Cliente cliente, Produto produto, Date data, Integer quantCompra, Double valorTotal) {
       this.id = id;
       this.cliente = cliente;
       this.produto = produto;
       this.data = data;
       this.quantCompra = quantCompra;
       this.valorTotal = valorTotal;
    }
   
     @Id 
     @GeneratedValue(strategy=GenerationType.IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cpf")
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cod")
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data", length=13)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    @Column(name="quant_compra")
    public Integer getQuantCompra() {
        return this.quantCompra;
    }
    
    public void setQuantCompra(Integer quantCompra) {
        this.quantCompra = quantCompra;
    }

    
    @Column(name="valor_total", precision=17, scale=17)
    public Double getValorTotal() {
        return this.valorTotal;
    }
    
    public void setValorTotal(Double valorTotal) {
        this.valorTotal = valorTotal;
    }




}